### ISSUE TITLE
Canonical naming 

### ISSUE THREAD

**Issue by virtualritz** [virtualritz/after-effects#34]
See the [Rust API Guidelines on naming](https://rust-lang.github.io/api-guidelines/naming.html).

Just while going through #33, I saw a bunch of stuff that doesn't adhere to it.

For example, `aeio::Handle` is now `aeio::AEIOHandle`.

This is ugly for two reasons.

1. Rust naming guidelines say `aeio::AEIOHandle` should rather be named `aeio::AeIoHandle`.

2. However, consider `std::io::Cursor`. This is *not* named `std::io::IoCursor`.
   Or `tokio::io::DumplexStream` is not called `tokio::io::IoDuplexStream`.

   I.e. the module namespace is *not* repeated as a prefix on types in that module. This is not mentioned in the above document but kind of an unwritten rule, if you look at naming conventions used for structs in the `std` lib and common crates.

**Comment by AdrianEddy** [comment]
Right, good point, I'll correct that in the next update.
It will be more clear once there's less C code, and more pure Rust code in the bindings interface

**Comment by virtualritz** [comment]
Cheers! 😀
