### ISSUE TITLE
Layer::bit_depth() is incorrect

### ISSUE THREAD

**Issue by fadaaszhi** [virtualritz/after-effects#58]
This expression used to calculate the bit depth of a layer in [`Layer::bit_depth()`](https://github.com/virtualritz/after-effects/blob/master/after-effects/src/pf/layer.rs#L256-L265) is incorrect:
```rs
(self.row_bytes().abs() as f32 / self.width() as f32).floor() as i16 / 4 * 8
```
A layer's `rowbytes` isn't related to its `width` in that way.

Here's an example case using the `examples/sdk_noise` plugin with assertions enabled:
1. Create a 1920x1080 comp
2. Add a comp-sized solid to it
3. Set the x-position of the solid to 2800
4. Set the project to 8 bpc
5. Apply the "SDK Noise" plugin to the solid

The result is
![image](https://github.com/user-attachments/assets/d9fc1dcd-5329-41d4-8039-d6e05ff49ec2)
This happens because the input layer has `rowbytes=7680` and `width=273`, meaning the method calculates the bit depth to be 56

**Comment by AdrianEddy** [comment]
I implemented it like that because of many inconsistencies between Premiere and After Effects. For example, 32-bit float layers in Premiere don't have the flags set and they are reported as 8-bit.

I fixed it in 7f666cef8355b67ca313136887503f7c7404c0f1
