### ISSUE TITLE
PF_Precision_* from Params_Utils.h seems like to be missing

### ISSUE THREAD

**Issue by BeezBeez** [virtualritz/after-effects#59]
Hello,

While adding float slider parameters I've noticed the enums from PF_Precision are missing.
I have forked the after-effect repo on my side to try to create the bindings but didn't managed to compile the project.

It was complaining of cstdint and string.h missing while generating the bindings. Even after adding the required include directories (On Windows). Can you write any documentation about how to regenerate/customize the bindings to easily contribute to your project on Windows and Mac. I would love to help you.

Thank you very much for this initiative, it's x1000 more pleasant to work with Rust ecosystem to create adobe plugins than the old 90s C++ !

**Comment by virtualritz** [comment]
The issue you describe seems purely `bindgen`-related.
Google is your friend. E.g. https://www.reddit.com/r/rust/s/DYdG9cNcEt

Alternatively open an issue in the ,[`bindgen` repo](https://github.com/rust-lang/rust-bindgen/issues).

**Comment by AdrianEddy** [comment]
Added in b2472cc4252033a5d6034d64e25ad0dcafad510e
