### ISSUE TITLE
examples/rust_gpu debug build freezes AE's viewport on Windows

### ISSUE THREAD

**Issue by fadaaszhi** [virtualritz/after-effects#61]
Hi, I can't get the debug build of examples/rust_gpu working on Windows.

I built it with `just build`. When I apply the effect to a layer inside After Effects, it freezes the comp viewer without freezing the rest of the UI. Removing the effect doesn't unfreeze the comp viewer, nor does changing compositions, etc.

If I build it with `just release`, it works fine inside After Effects without freezing the comp viewer.

This issue doesn't happen with the other examples I tried like examples/simplest and examples/transformer. The issue also doesn't happen on macOS.

Is there a way to get the debug build to work?
Thanks

**Comment by AdrianEddy** [comment]
I don't know why this happens and I was unable to debug it. There's a note about it at the very top of that file.
https://github.com/virtualritz/after-effects/blob/master/examples/rust_gpu/src/lib.rs#L10
