### ISSUE TITLE
Premiere suites cannot be used within After Effects plugins without some trickery

### ISSUE THREAD

**Issue by valadaptive** [virtualritz/after-effects#65]
The `PICA_BASIC_SUITE` thread-local in the `premiere` crate is separate from the one in the `after-effects` crate, and so it doesn't get initialized when the plugin does.

Attempting to acquire any Premiere suite will first try to access `PICA_BASIC_SUITE`, which will fail as it has never been initialized and is still null.

Getting around this requires some trickery:

```rust
// Careful! If you do a `let _ = ...` ("wildcard") binding, it will drop the PicaBasicSuite immediately and set the `PICA_BASIC_SUITE` thread-local variable back to null. You need to ensure the binding lives long enough for you to acquire whichever suite you want.
let _pica_suite = premiere::PicaBasicSuite::from_sp_basic_suite_raw(in_data.pica_basic_suite_ptr() as _);
let string_suite = premiere::suites::PrString::new()?;
```

**Comment by virtualritz** [comment]
If a suite depends on another suite to initialize I only see the option of passing the former during initialization to the latter.

We can model this with lifetimes and `Phantomdata` in which case the dependent shite does not need to hold a reference, the compiler takes care of it. But it does pollute the API with lifetimes.

The other option is to internally `Arc`-wrap the suite to make Clone cheap and pass a clone to the dependent suite.

**Comment by AdrianEddy** [comment]
Hmm, what's the use case of any Premiere suite when running in After Effects? I'm not sure I understand, I was under impression that Premiere suites are Premiere-only (contrary to AE suites, which are useful in Premiere too)

**Comment by valadaptive** [comment]
AEGP suites are not accessible in Premiere, and some functionality is exposed in separate AEGP and Premiere suites (e.g. [getting a window handle](https://github.com/valadaptive/ntsc-rs/blob/76166cb14de444c1c5159bf5765b75490ead5752/crates/ae-plugin/src/lib.rs#L727-L755)).

**Comment by AdrianEddy** [comment]
So here's my idea. What do you think?
It will work reliably, because the macro is always compiled in the final user's crate (the plugin code), so we're guaranteed that the premiere's build.rs has already ran

Another option is to just add a feature to `after-effects` called `with_premiere` and make user responsible for enabling it

```diff
--- a/premiere/build.rs
+++ b/premiere/build.rs
@@ -10,4 +10,6 @@ fn main() {
         // Likely using the built-in bindings
         println!("cargo:rustc-cfg=has_ae_sdk");
     }
+
+    println!("cargo:rustc-env=RUST_PREMIERE_USED=true");^M
 }
--- a/after-effects/src/plugin_base.rs
+++ b/after-effects/src/plugin_base.rs
@@ -229,6 +229,11 @@ macro_rules! define_effect {
             let in_data = InData::from_raw(in_data_ptr);
             let out_data = OutData::from_raw(out_data_ptr);

+            let mut _pr_pica = None;
+            if in_data.is_premiere() && option_env!("RUST_PREMIERE_USED") == Some("true") {
+                _pr_pica = Some(::premiere::PicaBasicSuite::from_sp_basic_suite_raw(in_data.pica_basic_suite_ptr() as _));
+            }
+
             let cmd = RawCommand::from(cmd);

             // Allocate or restore global data pointer
```

**Comment by AdrianEddy** [comment]
I added it like that since there were no better ideas acbd5ff755974242036562a90077053918e8a477
