### ISSUE TITLE
How safe is using `WorldFlags::RESERVED1` for checking bit depth?

### ISSUE THREAD

**Issue by fadaaszhi** [virtualritz/after-effects#74]
(I would have created a discussion for this instead of an issue but those aren't enabled for this repository.)

I saw that `WorldFlags::RESERVED1` is used to check if a layer is 32 bpc: https://github.com/virtualritz/after-effects/blob/c70729aa569e5a67c9556e452923072be059f4b8/after-effects/src/pf/layer.rs#L260-L261 and that the flag was first used this way in this commit: https://github.com/virtualritz/after-effects/blob/26e4c31ae499a2437de871d76d3d841dfd6424f1/src/pf.rs#L142-L143
I can't find reference to this functionality anywhere in the SDK (which makes sense since it's a reserved flag after all), so how was it known to use this flag for this purpose? What do the other 7 reserved `WorldFlags` represent? Is there a chance this'll stop working in the future at some point, since it doesn't seem to be documented anywhere?

**Comment by virtualritz** [comment]
I would think that if the notoriously lacking SDK docs don't explain it, I either:

* Copied this code from an SDK example.

* Someone on the Ae SDK mailing list enlightened me.

* It was used in our AtomKraft for AE plug-in which means that it could have also come to our knowledge by either the above two points or some reverse-engineering the main author of that code did at the time.

In any case, I think this safe as I worked on another plugin in Rust for a year, that integrated a 3D renderer, and `f32` support was essential.

The initial publish of this crate was part of that (when I stopped work on the plugin).

**Comment by fadaaszhi** [comment]
Thanks for the detailed answer!

> I think this safe as I worked on another plugin in Rust for a year

But that doesn't say anything about whether it'll work in the future (I know, I am probably being overly pessimistic here).

AdrianEddy added the two `match` expressions that calculate the bit depth of the layer, playing 100% by the SDK's books, so would it be fine to remove the flag checking in favor of the pixel format checking?

**Comment by AdrianEddy** [comment]
> AdrianEddy added the two `match` expressions that calculate the bit depth of the layer, playing 100% by the SDK's books, so would it be fine to remove the flag checking in favor of the pixel format checking?

That's not a good idea. The problem is that Adobe does stupid things and I saw cases where the layer was 32-bit but the standard SDK tools returned 8 bit. And it was not only bit depth, there was lots of other ridiculous cases like that throughout the entire SDK

**Comment by fadaaszhi** [comment]
> I saw cases where the layer was 32-bit but the standard SDK tools returned 8 bit.

What! 🤯 I guess it gets left as is then. Thanks for the replies!
